squash v0.2

diff --git a/squash b/squash
--- a/squash
+++ b/squash
@@ -4,7 +4,7 @@
 Help()
 {
   echo "help"
-  echo "  squash src_branch dst_branch : squash-merge srg into dst with a commit with the name of the src branch"
+  echo "  squash src_branch : squash-merge src_branch into current branch"
   echo "  squash -h : help"
 }
 
@@ -26,50 +26,34 @@ if [ -z "$(git rev-parse --is-inside-work-tree 2>/dev/null)" ]; then
 fi
 
 # read input
-SRC_BRANCH=$1
-DST_BRANCH=$2
+BRANCH=$1
 
-# check arguments are not null
-if [ -z "$SRC_BRANCH" ]; then
+if [ -z "$BRANCH" ]; then
   echo "Error: missing argument src_branch"
   exit 1
 fi
-if [ -z "$DST_BRANCH" ]; then
-  echo "Error: missing argument dst_branch"
-  exit 1
-fi
-if [ "$SRC_BRANCH" == "$DST_BRANCH" ]; then
-  echo "Error: same src and dst branch"
-  exit 1
-fi
-
-# check branches
 if [ -z "$(git rev-parse --verify $SRC_BRANCH 2>/dev/null)" ]; then
   echo "Error: branch $SRC_BRANCH does not exist"
-  exit 1
-fi
-if [ -z "$(git rev-parse --verify $DST_BRANCH 2>/dev/null)" ]; then
-  echo "Error: branch $DST_BRANCH does not exist"
   exit 1
 fi
 
 # main program
 
-TMP_BRANCH=$SRC_BRANCH-squash
+CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
 
-git checkout -b $TMP_BRANCH $DST_BRANCH
+echo "Squashing branch $BRANCH into $CURRENT_BRANCH..."
+
+git merge --squash $BRANCH
 if [ $? -ne 0 ]; then
-  git checkout $TMP_BRANCH
-  if [ $? -ne 0 ]; then
-    echo "Error: aborting squash..."
-    exit 1
-  fi
+  echo "Error: aborting squash..."
+  exit 1
 fi
 
-git merge --squash $SRC_BRANCH
-git commit -m "squash $SRC_BRANCH"
+# append branch name to squash msg
+cat > squash_msg.tmp <<- EOM
+$src
+$(cat .git/SQUASH_MSG)
+EOM
 
-git checkout $DST_BRANCH
-git merge $TMP_BRANCH
-
-git branch -D $TMP_BRANCH
+git commit -F squash_msg.tmp
+rm squash_msg.tmp
